### ISSUE TITLE
Por que esta liberando essa SRC?

### ISSUE THREAD

**Issue by IZ44KPvP** [Floodeer/SkyWars#1]
Oque aconteceu porque está liberando a Source Code desse plugin?

**Comment by Floodeer** [comment]
Todos os meus projetos frees tem source code em algum lugar, além disso, o código não está muito estável.

**Comment by IZ44KPvP** [comment]
Ah, sim entendo, sem problemas se eu fazer uma edição para meu servidor? garanto que não vou remover seus créditos da plugin.yml

**Comment by Floodeer** [comment]
Claro, pode fazer.
