### ISSUE TITLE
Nightcrawl

### ISSUE THREAD

**Issue by IZ44KPvP** [Floodeer/SkyWars#2]
O Servidor não irá mais abrir?

**Comment by Floodeer** [comment]
To um pouco sem tempo, não consigo arrumar um fim de semana que todos staffs estejam disponíveis pra abrir uma BETA de novo, provavelmente vou abrir pra testar na próxima semana.

**Comment by IZ44KPvP** [comment]
Ah, entendi... Boa sorte ai, se precisar de qualquer ajuda chama no skype: izacraftgamer
